version: "3.8"
services:
  app:
    build:
      context: ./front
      dockerfile: ../Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
